# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PersonelGuncelle.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(778, 464)
        Dialog.setMinimumSize(QtCore.QSize(778, 464))
        Dialog.setMaximumSize(QtCore.QSize(778, 464))
        self.buttonPersonelDuzenle = QtWidgets.QPushButton(Dialog)
        self.buttonPersonelDuzenle.setGeometry(QtCore.QRect(500, 390, 261, 51))
        self.buttonPersonelDuzenle.setMinimumSize(QtCore.QSize(261, 51))
        self.buttonPersonelDuzenle.setMaximumSize(QtCore.QSize(261, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPersonelDuzenle.setFont(font)
        self.buttonPersonelDuzenle.setObjectName("buttonPersonelDuzenle")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(366, 41, 21, 411))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(13, 41, 341, 391))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFotograf = QtWidgets.QLabel(self.layoutWidget)
        self.labelFotograf.setMinimumSize(QtCore.QSize(339, 343))
        self.labelFotograf.setMaximumSize(QtCore.QSize(339, 343))
        self.labelFotograf.setAutoFillBackground(False)
        self.labelFotograf.setStyleSheet("")
        self.labelFotograf.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelFotograf.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelFotograf.setText("")
        self.labelFotograf.setObjectName("labelFotograf")
        self.verticalLayout.addWidget(self.labelFotograf)
        self.buttonFotografYukle = QtWidgets.QPushButton(self.layoutWidget)
        self.buttonFotografYukle.setMinimumSize(QtCore.QSize(339, 40))
        self.buttonFotografYukle.setMaximumSize(QtCore.QSize(339, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonFotografYukle.setFont(font)
        self.buttonFotografYukle.setObjectName("buttonFotografYukle")
        self.verticalLayout.addWidget(self.buttonFotografYukle)
        self.labelPersonelGuncelle = QtWidgets.QLabel(Dialog)
        self.labelPersonelGuncelle.setGeometry(QtCore.QRect(290, 0, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.labelPersonelGuncelle.setFont(font)
        self.labelPersonelGuncelle.setObjectName("labelPersonelGuncelle")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(10, 10, 271, 21))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(490, 10, 271, 21))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.editAciklama = QtWidgets.QLineEdit(Dialog)
        self.editAciklama.setGeometry(QtCore.QRect(500, 340, 261, 41))
        self.editAciklama.setMinimumSize(QtCore.QSize(261, 41))
        self.editAciklama.setMaximumSize(QtCore.QSize(261, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editAciklama.setFont(font)
        self.editAciklama.setText("")
        self.editAciklama.setClearButtonEnabled(True)
        self.editAciklama.setObjectName("editAciklama")
        self.splitter = QtWidgets.QSplitter(Dialog)
        self.splitter.setGeometry(QtCore.QRect(500, 50, 261, 241))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.editTcNo = QtWidgets.QLineEdit(self.splitter)
        self.editTcNo.setMinimumSize(QtCore.QSize(261, 36))
        self.editTcNo.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editTcNo.setFont(font)
        self.editTcNo.setText("")
        self.editTcNo.setClearButtonEnabled(True)
        self.editTcNo.setObjectName("editTcNo")
        self.editAd = QtWidgets.QLineEdit(self.splitter)
        self.editAd.setMinimumSize(QtCore.QSize(261, 36))
        self.editAd.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editAd.setFont(font)
        self.editAd.setText("")
        self.editAd.setClearButtonEnabled(True)
        self.editAd.setObjectName("editAd")
        self.editSoyad = QtWidgets.QLineEdit(self.splitter)
        self.editSoyad.setMinimumSize(QtCore.QSize(261, 36))
        self.editSoyad.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editSoyad.setFont(font)
        self.editSoyad.setClearButtonEnabled(True)
        self.editSoyad.setObjectName("editSoyad")
        self.editYas = QtWidgets.QLineEdit(self.splitter)
        self.editYas.setMinimumSize(QtCore.QSize(261, 36))
        self.editYas.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editYas.setFont(font)
        self.editYas.setText("")
        self.editYas.setClearButtonEnabled(True)
        self.editYas.setObjectName("editYas")
        self.editPozisyon = QtWidgets.QLineEdit(self.splitter)
        self.editPozisyon.setMinimumSize(QtCore.QSize(261, 36))
        self.editPozisyon.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editPozisyon.setFont(font)
        self.editPozisyon.setText("")
        self.editPozisyon.setClearButtonEnabled(True)
        self.editPozisyon.setObjectName("editPozisyon")
        self.editTelefonNo = QtWidgets.QLineEdit(self.splitter)
        self.editTelefonNo.setMinimumSize(QtCore.QSize(261, 36))
        self.editTelefonNo.setMaximumSize(QtCore.QSize(261, 36))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.editTelefonNo.setFont(font)
        self.editTelefonNo.setText("")
        self.editTelefonNo.setClearButtonEnabled(True)
        self.editTelefonNo.setObjectName("editTelefonNo")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 440, 371, 16))
        self.label.setObjectName("label")
        self.layoutWidget_2 = QtWidgets.QWidget(Dialog)
        self.layoutWidget_2.setGeometry(QtCore.QRect(530, 300, 231, 31))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonGunduzGuncelle = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButtonGunduzGuncelle.setMinimumSize(QtCore.QSize(115, 22))
        self.radioButtonGunduzGuncelle.setMaximumSize(QtCore.QSize(115, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonGunduzGuncelle.setFont(font)
        self.radioButtonGunduzGuncelle.setObjectName("radioButtonGunduzGuncelle")
        self.horizontalLayout_2.addWidget(self.radioButtonGunduzGuncelle)
        self.radioButtonGeceGuncelle = QtWidgets.QRadioButton(self.layoutWidget_2)
        self.radioButtonGeceGuncelle.setMinimumSize(QtCore.QSize(114, 22))
        self.radioButtonGeceGuncelle.setMaximumSize(QtCore.QSize(114, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.radioButtonGeceGuncelle.setFont(font)
        self.radioButtonGeceGuncelle.setObjectName("radioButtonGeceGuncelle")
        self.horizontalLayout_2.addWidget(self.radioButtonGeceGuncelle)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(404, 52, 91, 321))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelTcNo = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTcNo.setFont(font)
        self.labelTcNo.setObjectName("labelTcNo")
        self.verticalLayout_2.addWidget(self.labelTcNo)
        self.labelAd = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelAd.setFont(font)
        self.labelAd.setObjectName("labelAd")
        self.verticalLayout_2.addWidget(self.labelAd)
        self.labelSoyad = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelSoyad.setFont(font)
        self.labelSoyad.setObjectName("labelSoyad")
        self.verticalLayout_2.addWidget(self.labelSoyad)
        self.labelYas = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelYas.setFont(font)
        self.labelYas.setObjectName("labelYas")
        self.verticalLayout_2.addWidget(self.labelYas)
        self.labelPozisyon = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelPozisyon.setFont(font)
        self.labelPozisyon.setObjectName("labelPozisyon")
        self.verticalLayout_2.addWidget(self.labelPozisyon)
        self.labelTelefonNo = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelTelefonNo.setFont(font)
        self.labelTelefonNo.setObjectName("labelTelefonNo")
        self.verticalLayout_2.addWidget(self.labelTelefonNo)
        self.labelMesaiTipi = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelMesaiTipi.setFont(font)
        self.labelMesaiTipi.setObjectName("labelMesaiTipi")
        self.verticalLayout_2.addWidget(self.labelMesaiTipi)
        self.labelAciklama = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.labelAciklama.setFont(font)
        self.labelAciklama.setObjectName("labelAciklama")
        self.verticalLayout_2.addWidget(self.labelAciklama)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.buttonPersonelDuzenle.setText(_translate("Dialog", "PERSONELI GUNCELLE"))
        self.buttonFotografYukle.setText(_translate("Dialog", "Fotoğraf Yükle"))
        self.labelPersonelGuncelle.setText(_translate("Dialog", "PERSONEL GÜNCELLE"))
        self.label.setText(_translate("Dialog", "*Fotograf uzerinden yuz tanima ve kirpma gerceklesecegi icin uzun surebilir."))
        self.radioButtonGunduzGuncelle.setText(_translate("Dialog", "Gündüz"))
        self.radioButtonGeceGuncelle.setText(_translate("Dialog", "Gece"))
        self.labelTcNo.setText(_translate("Dialog", "T.C. No"))
        self.labelAd.setText(_translate("Dialog", "Ad"))
        self.labelSoyad.setText(_translate("Dialog", "Soyad"))
        self.labelYas.setText(_translate("Dialog", "Yaş"))
        self.labelPozisyon.setText(_translate("Dialog", "Pozisyon"))
        self.labelTelefonNo.setText(_translate("Dialog", "Telefon No"))
        self.labelMesaiTipi.setText(_translate("Dialog", "Mesai Tipi"))
        self.labelAciklama.setText(_translate("Dialog", "Açıklama"))


