# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Personel.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1022, 649)
        Dialog.setMinimumSize(QtCore.QSize(1022, 649))
        Dialog.setMaximumSize(QtCore.QSize(1920, 1080))
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(Dialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1002, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.scrollAreaWidgetContents)
        self.tableWidget.setMinimumSize(QtCore.QSize(603, 395))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.gridLayout.addWidget(self.tableWidget, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonPersonelEkle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonPersonelEkle.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonPersonelEkle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.buttonPersonelEkle.setFont(font)
        self.buttonPersonelEkle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonPersonelEkle.setObjectName("buttonPersonelEkle")
        self.verticalLayout_2.addWidget(self.buttonPersonelEkle)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.buttonPersonelSil = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonPersonelSil.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonPersonelSil.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPersonelSil.setFont(font)
        self.buttonPersonelSil.setObjectName("buttonPersonelSil")
        self.verticalLayout_2.addWidget(self.buttonPersonelSil)
        self.line_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.buttonPersonelGuncelle = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonPersonelGuncelle.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonPersonelGuncelle.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPersonelGuncelle.setFont(font)
        self.buttonPersonelGuncelle.setObjectName("buttonPersonelGuncelle")
        self.verticalLayout_2.addWidget(self.buttonPersonelGuncelle)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.buttonPersonelGirisSaatleri = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.buttonPersonelGirisSaatleri.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPersonelGirisSaatleri.setFont(font)
        self.buttonPersonelGirisSaatleri.setObjectName("buttonPersonelGirisSaatleri")
        self.verticalLayout_2.addWidget(self.buttonPersonelGirisSaatleri)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 2, 0, 1, 3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelPersonelEkrani = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.labelPersonelEkrani.setFont(font)
        self.labelPersonelEkrani.setObjectName("labelPersonelEkrani")
        self.horizontalLayout.addWidget(self.labelPersonelEkrani)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(150, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        self.editAranacakTcNo = QtWidgets.QLineEdit(Dialog)
        self.editAranacakTcNo.setMinimumSize(QtCore.QSize(100, 30))
        self.editAranacakTcNo.setMaximumSize(QtCore.QSize(177, 30))
        self.editAranacakTcNo.setClearButtonEnabled(True)
        self.editAranacakTcNo.setObjectName("editAranacakTcNo")
        self.gridLayout_3.addWidget(self.editAranacakTcNo, 0, 3, 1, 1)
        self.buttonPersonelAra = QtWidgets.QPushButton(Dialog)
        self.buttonPersonelAra.setMinimumSize(QtCore.QSize(75, 30))
        self.buttonPersonelAra.setMaximumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.buttonPersonelAra.setFont(font)
        self.buttonPersonelAra.setObjectName("buttonPersonelAra")
        self.gridLayout_3.addWidget(self.buttonPersonelAra, 0, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 0, 0, 1, 3)
        self.labelToplamPersonelSayisi = QtWidgets.QLabel(Dialog)
        self.labelToplamPersonelSayisi.setObjectName("labelToplamPersonelSayisi")
        self.gridLayout_2.addWidget(self.labelToplamPersonelSayisi, 3, 0, 1, 2)
        self.line_8 = QtWidgets.QFrame(Dialog)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout_2.addWidget(self.line_8, 1, 2, 1, 1)
        self.line_7 = QtWidgets.QFrame(Dialog)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_2.addWidget(self.line_7, 1, 1, 1, 1)
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "T.C. No"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Adı"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Soyadı"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Yaşı"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Pozisyonu"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Telefon No"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Mesai Tipi"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Açıklama"))
        self.buttonPersonelEkle.setText(_translate("Dialog", "Personel Ekle"))
        self.buttonPersonelSil.setText(_translate("Dialog", "Personeli Sil"))
        self.buttonPersonelGuncelle.setText(_translate("Dialog", "Personeli Güncelle"))
        self.buttonPersonelGirisSaatleri.setText(_translate("Dialog", "Personel Giriş/Çıkış Kayıtlari"))
        self.labelPersonelEkrani.setText(_translate("Dialog", "PERSONEL EKRANI"))
        self.label.setText(_translate("Dialog", "Aranacak Personel T.C. Numarasi"))
        self.buttonPersonelAra.setText(_translate("Dialog", "ARA"))
        self.labelToplamPersonelSayisi.setText(_translate("Dialog", "Toplam Personel Sayisi:"))


